package com.suganth.infotimes.fragments

import android.os.Bundle
import android.view.View
import android.webkit.WebViewClient
import androidx.fragment.app.Fragment
import androidx.navigation.fragment.navArgs
import com.google.android.material.snackbar.Snackbar
import com.suganth.infotimes.R
import com.suganth.infotimes.ui.NewsActivity
import com.suganth.infotimes.ui.NewsViewModel
import kotlinx.android.synthetic.main.fragment_article.*

class ArticlesNewsFragment: Fragment(R.layout.fragment_article) {

    lateinit var viewModel:NewsViewModel

    /**
     * Now ,we need to receive three different articles passed from
     * our three different fragment with helps of  class generated by nav component
     */
    val args: ArticlesNewsFragmentArgs by navArgs()

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        viewModel = (activity as NewsActivity).viewModel
        val article = args.article
        webView.apply {
            webViewClient = WebViewClient()
            loadUrl(article.url)
        }

        fab.setOnClickListener {
            viewModel.saveArticle(article)
            Snackbar.make(view, "Article saved successfully", Snackbar.LENGTH_LONG).show()
        }
    }
}